/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountStatus = { 'active' : null } |
  { 'disabled' : null };
export interface AdminSettingsView { 'otherCosts' : bigint }
export interface AdminUserRow {
  'id' : UserId,
  'accountStatus' : AccountStatus,
  'lastActiveAt' : Timestamp,
  'name' : string,
  'email' : [] | [string],
  'subscriptionStatus' : SubscriptionStatusView,
  'aiGenerations' : bigint,
  'totalAmountSpent' : bigint,
  'registeredAt' : Timestamp,
}
export type AnalyticsEventType = { 'generationCompleted' : null } |
  { 'subscriptionStarted' : null } |
  { 'registration' : null } |
  { 'generationStarted' : null } |
  { 'login' : null } |
  { 'subscriptionRenewed' : null } |
  { 'generationFailed' : null } |
  { 'paymentCompleted' : null } |
  { 'subscriptionCancelled' : null };
export interface AnalyticsEventView {
  'id' : bigint,
  'metadata' : [] | [string],
  'user' : UserId,
  'timestamp' : Timestamp,
  'eventType' : AnalyticsEventType,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface ChartPoint {
  'activeUsers' : bigint,
  'date' : Timestamp,
  'retentionRate' : [] | [number],
  'newUsers' : bigint,
}
export type ChartRange = { 'last90Days' : null } |
  { 'last7Days' : null } |
  { 'last30Days' : null };
export interface ChartSeries {
  'range' : ChartRange,
  'points' : Array<ChartPoint>,
}
export interface ChatConversationView {
  'id' : bigint,
  'title' : string,
  'owner' : UserId,
  'createdAt' : Timestamp,
}
export interface ChatMessageView {
  'id' : bigint,
  'content' : string,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'role' : ChatRole,
  'conversationId' : bigint,
}
export type ChatResult = { 'ok' : { 'message' : string } } |
  { 'providerNotConfigured' : null };
export type ChatRole = { 'user' : null } |
  { 'assistant' : null };
export type ConnectionStatus = { 'notConnected' : null } |
  { 'connected' : null };
export interface CsvExport { 'content' : string, 'filename' : string }
export interface DashboardOverview {
  'premiumUsers' : bigint,
  'newUsersToday' : bigint,
  'activeUsersThisMonth' : bigint,
  'activeUsersToday' : bigint,
  'totalGenerations' : bigint,
  'totalUsers' : bigint,
  'totalRevenue' : RevenueSummary,
  'estimatedProfit' : ProfitSummary,
}
export type DateRange = { 'today' : null } |
  { 'last90Days' : null } |
  { 'custom' : { 'to' : Timestamp, 'from' : Timestamp } } |
  { 'last7Days' : null } |
  { 'last30Days' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface FeatureUsage {
  'numberOfUsers' : bigint,
  'failedGenerations' : bigint,
  'tool' : string,
  'totalGenerations' : bigint,
  'successfulGenerations' : bigint,
  'averageGenerationsPerUser' : [] | [number],
}
export interface FileUpload {
  'name' : string,
  'mimeType' : string,
  'sizeBytes' : bigint,
}
export type FileUploadError = { 'notAuthorized' : null } |
  { 'tooLarge' : bigint } |
  { 'unsupportedType' : string };
export type GenerationStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export interface GenerationView {
  'id' : bigint,
  'status' : GenerationStatus,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'tool' : string,
  'projectId' : bigint,
}
export type ImageGenerationResult = { 'ok' : { 'generationId' : bigint } } |
  { 'providerNotConfigured' : null };
export interface ProfitSummary {
  'status' : ConnectionStatus,
  'otherCosts' : bigint,
  'aiApiCost' : bigint,
  'totalRevenue' : bigint,
  'profitMargin' : [] | [number],
  'estimatedProfit' : bigint,
}
export interface ProjectView {
  'id' : bigint,
  'owner' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
}
export type Result = { 'ok' : SavedFileView } |
  { 'err' : FileUploadError };
export type Result_1 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface RevenueSummary {
  'status' : ConnectionStatus,
  'today' : bigint,
  'total' : bigint,
  'subscription' : bigint,
  'thisWeek' : bigint,
  'oneTime' : bigint,
  'thisMonth' : bigint,
  'advertisement' : bigint,
}
export interface SavedFileView {
  'id' : bigint,
  'owner' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'mimeType' : string,
  'projectId' : [] | [bigint],
  'sizeBytes' : bigint,
}
export interface SubscriptionMetrics {
  'premiumUsers' : bigint,
  'subscriptionRevenue' : RevenueSummary,
  'newSubscriptions' : bigint,
  'renewals' : bigint,
  'freeUsers' : bigint,
  'activeSubscriptions' : bigint,
  'cancelledSubscriptions' : bigint,
}
export interface SubscriptionStatusView {
  'expiresAt' : [] | [Timestamp],
  'owner' : UserId,
  'tier' : SubscriptionTier,
}
export type SubscriptionTier = { 'pro' : null } |
  { 'free' : null };
export type Timestamp = bigint;
export interface UserDetail {
  'metrics' : UserMetrics,
  'user' : AdminUserRow,
  'featureUsage' : Array<FeatureUsage>,
  'recentEvents' : Array<AnalyticsEventView>,
}
export type UserId = Principal;
export interface UserMetrics {
  'newToday' : bigint,
  'newThisWeek' : bigint,
  'monthlyActive' : bigint,
  'newThisMonth' : bigint,
  'totalRegistered' : bigint,
  'dailyActive' : bigint,
  'retentionRate' : [] | [number],
  'returningUsers' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettingsView {
  'theme' : string,
  'notificationsEnabled' : boolean,
  'displayName' : string,
  'owner' : UserId,
  'email' : [] | [string],
  'language' : string,
}
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addMessage' : ActorMethod<[bigint, string], [] | [ChatMessageView]>,
  'adminExportAnalyticsCsv' : ActorMethod<[[] | [DateRange]], CsvExport>,
  'adminExportUsersCsv' : ActorMethod<
    [[] | [string], [] | [DateRange]],
    CsvExport
  >,
  'adminGetChartSeries' : ActorMethod<[ChartRange], ChartSeries>,
  'adminGetDashboardOverview' : ActorMethod<[], DashboardOverview>,
  'adminGetFeatureUsage' : ActorMethod<[], Array<FeatureUsage>>,
  'adminGetSettings' : ActorMethod<[], AdminSettingsView>,
  'adminGetSubscriptionMetrics' : ActorMethod<[], SubscriptionMetrics>,
  'adminGetUserDetail' : ActorMethod<[Principal], [] | [UserDetail]>,
  'adminGetUserMetrics' : ActorMethod<[], UserMetrics>,
  'adminListUsers' : ActorMethod<
    [[] | [string], [] | [DateRange]],
    Array<AdminUserRow>
  >,
  'adminUpdateOtherCosts' : ActorMethod<[bigint], AdminSettingsView>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'chat' : ActorMethod<[bigint, string], ChatResult>,
  'createConversation' : ActorMethod<[string], ChatConversationView>,
  'createProject' : ActorMethod<[string], ProjectView>,
  'deleteConversation' : ActorMethod<[bigint], boolean>,
  'deleteFile' : ActorMethod<[bigint], boolean>,
  'deleteProject' : ActorMethod<[bigint], boolean>,
  'execute' : ActorMethod<[string], Result__1>,
  'generateImage' : ActorMethod<[bigint, string], ImageGenerationResult>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSubscription' : ActorMethod<[], [] | [SubscriptionStatusView]>,
  'getUserSettings' : ActorMethod<[], [] | [UserSettingsView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listConversations' : ActorMethod<[], Array<ChatConversationView>>,
  'listFiles' : ActorMethod<[], Array<SavedFileView>>,
  'listGenerations' : ActorMethod<[], Array<GenerationView>>,
  'listMessages' : ActorMethod<[bigint], Array<ChatMessageView>>,
  'listProjects' : ActorMethod<[], Array<ProjectView>>,
  'renameProject' : ActorMethod<[bigint, string], [] | [ProjectView]>,
  'saveFile' : ActorMethod<[[] | [bigint], FileUpload], Result>,
  'schema' : ActorMethod<[], string>,
  'updateSubscription' : ActorMethod<
    [SubscriptionTier, [] | [Timestamp]],
    SubscriptionStatusView
  >,
  'updateUserSettings' : ActorMethod<
    [string, boolean, string, [] | [string], string],
    UserSettingsView
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];