/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const ChatRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const ChatMessageView = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'role' : ChatRole,
  'conversationId' : IDL.Nat,
});
export const DateRange = IDL.Variant({
  'today' : IDL.Null,
  'last90Days' : IDL.Null,
  'custom' : IDL.Record({ 'to' : Timestamp, 'from' : Timestamp }),
  'last7Days' : IDL.Null,
  'last30Days' : IDL.Null,
});
export const CsvExport = IDL.Record({
  'content' : IDL.Text,
  'filename' : IDL.Text,
});
export const ChartRange = IDL.Variant({
  'last90Days' : IDL.Null,
  'last7Days' : IDL.Null,
  'last30Days' : IDL.Null,
});
export const ChartPoint = IDL.Record({
  'activeUsers' : IDL.Nat,
  'date' : Timestamp,
  'retentionRate' : IDL.Opt(IDL.Float64),
  'newUsers' : IDL.Nat,
});
export const ChartSeries = IDL.Record({
  'range' : ChartRange,
  'points' : IDL.Vec(ChartPoint),
});
export const ConnectionStatus = IDL.Variant({
  'notConnected' : IDL.Null,
  'connected' : IDL.Null,
});
export const RevenueSummary = IDL.Record({
  'status' : ConnectionStatus,
  'today' : IDL.Nat,
  'total' : IDL.Nat,
  'subscription' : IDL.Nat,
  'thisWeek' : IDL.Nat,
  'oneTime' : IDL.Nat,
  'thisMonth' : IDL.Nat,
  'advertisement' : IDL.Nat,
});
export const ProfitSummary = IDL.Record({
  'status' : ConnectionStatus,
  'otherCosts' : IDL.Nat,
  'aiApiCost' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'profitMargin' : IDL.Opt(IDL.Float64),
  'estimatedProfit' : IDL.Nat,
});
export const DashboardOverview = IDL.Record({
  'premiumUsers' : IDL.Nat,
  'newUsersToday' : IDL.Nat,
  'activeUsersThisMonth' : IDL.Nat,
  'activeUsersToday' : IDL.Nat,
  'totalGenerations' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalRevenue' : RevenueSummary,
  'estimatedProfit' : ProfitSummary,
});
export const FeatureUsage = IDL.Record({
  'numberOfUsers' : IDL.Nat,
  'failedGenerations' : IDL.Nat,
  'tool' : IDL.Text,
  'totalGenerations' : IDL.Nat,
  'successfulGenerations' : IDL.Nat,
  'averageGenerationsPerUser' : IDL.Opt(IDL.Float64),
});
export const AdminSettingsView = IDL.Record({ 'otherCosts' : IDL.Nat });
export const SubscriptionMetrics = IDL.Record({
  'premiumUsers' : IDL.Nat,
  'subscriptionRevenue' : RevenueSummary,
  'newSubscriptions' : IDL.Nat,
  'renewals' : IDL.Nat,
  'freeUsers' : IDL.Nat,
  'activeSubscriptions' : IDL.Nat,
  'cancelledSubscriptions' : IDL.Nat,
});
export const UserMetrics = IDL.Record({
  'newToday' : IDL.Nat,
  'newThisWeek' : IDL.Nat,
  'monthlyActive' : IDL.Nat,
  'newThisMonth' : IDL.Nat,
  'totalRegistered' : IDL.Nat,
  'dailyActive' : IDL.Nat,
  'retentionRate' : IDL.Opt(IDL.Float64),
  'returningUsers' : IDL.Nat,
});
export const AccountStatus = IDL.Variant({
  'active' : IDL.Null,
  'disabled' : IDL.Null,
});
export const SubscriptionTier = IDL.Variant({
  'pro' : IDL.Null,
  'free' : IDL.Null,
});
export const SubscriptionStatusView = IDL.Record({
  'expiresAt' : IDL.Opt(Timestamp),
  'owner' : UserId,
  'tier' : SubscriptionTier,
});
export const AdminUserRow = IDL.Record({
  'id' : UserId,
  'accountStatus' : AccountStatus,
  'lastActiveAt' : Timestamp,
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'subscriptionStatus' : SubscriptionStatusView,
  'aiGenerations' : IDL.Nat,
  'totalAmountSpent' : IDL.Nat,
  'registeredAt' : Timestamp,
});
export const AnalyticsEventType = IDL.Variant({
  'generationCompleted' : IDL.Null,
  'subscriptionStarted' : IDL.Null,
  'registration' : IDL.Null,
  'generationStarted' : IDL.Null,
  'login' : IDL.Null,
  'subscriptionRenewed' : IDL.Null,
  'generationFailed' : IDL.Null,
  'paymentCompleted' : IDL.Null,
  'subscriptionCancelled' : IDL.Null,
});
export const AnalyticsEventView = IDL.Record({
  'id' : IDL.Nat,
  'metadata' : IDL.Opt(IDL.Text),
  'user' : UserId,
  'timestamp' : Timestamp,
  'eventType' : AnalyticsEventType,
});
export const UserDetail = IDL.Record({
  'metrics' : UserMetrics,
  'user' : AdminUserRow,
  'featureUsage' : IDL.Vec(FeatureUsage),
  'recentEvents' : IDL.Vec(AnalyticsEventView),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChatResult = IDL.Variant({
  'ok' : IDL.Record({ 'message' : IDL.Text }),
  'providerNotConfigured' : IDL.Null,
});
export const ChatConversationView = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'owner' : UserId,
  'createdAt' : Timestamp,
});
export const ProjectView = IDL.Record({
  'id' : IDL.Nat,
  'owner' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const ImageGenerationResult = IDL.Variant({
  'ok' : IDL.Record({ 'generationId' : IDL.Nat }),
  'providerNotConfigured' : IDL.Null,
});
export const UserSettingsView = IDL.Record({
  'theme' : IDL.Text,
  'notificationsEnabled' : IDL.Bool,
  'displayName' : IDL.Text,
  'owner' : UserId,
  'email' : IDL.Opt(IDL.Text),
  'language' : IDL.Text,
});
export const SavedFileView = IDL.Record({
  'id' : IDL.Nat,
  'owner' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'mimeType' : IDL.Text,
  'projectId' : IDL.Opt(IDL.Nat),
  'sizeBytes' : IDL.Nat,
});
export const GenerationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const GenerationView = IDL.Record({
  'id' : IDL.Nat,
  'status' : GenerationStatus,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'tool' : IDL.Text,
  'projectId' : IDL.Nat,
});
export const FileUpload = IDL.Record({
  'name' : IDL.Text,
  'mimeType' : IDL.Text,
  'sizeBytes' : IDL.Nat,
});
export const FileUploadError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'tooLarge' : IDL.Nat,
  'unsupportedType' : IDL.Text,
});
export const Result = IDL.Variant({
  'ok' : SavedFileView,
  'err' : FileUploadError,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(ChatMessageView)], []),
  'adminExportAnalyticsCsv' : IDL.Func(
      [IDL.Opt(DateRange)],
      [CsvExport],
      ['query'],
    ),
  'adminExportUsersCsv' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(DateRange)],
      [CsvExport],
      ['query'],
    ),
  'adminGetChartSeries' : IDL.Func([ChartRange], [ChartSeries], ['query']),
  'adminGetDashboardOverview' : IDL.Func([], [DashboardOverview], ['query']),
  'adminGetFeatureUsage' : IDL.Func([], [IDL.Vec(FeatureUsage)], ['query']),
  'adminGetSettings' : IDL.Func([], [AdminSettingsView], ['query']),
  'adminGetSubscriptionMetrics' : IDL.Func(
      [],
      [SubscriptionMetrics],
      ['query'],
    ),
  'adminGetUserDetail' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserDetail)],
      ['query'],
    ),
  'adminGetUserMetrics' : IDL.Func([], [UserMetrics], ['query']),
  'adminListUsers' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(DateRange)],
      [IDL.Vec(AdminUserRow)],
      ['query'],
    ),
  'adminUpdateOtherCosts' : IDL.Func([IDL.Nat], [AdminSettingsView], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'chat' : IDL.Func([IDL.Nat, IDL.Text], [ChatResult], []),
  'createConversation' : IDL.Func([IDL.Text], [ChatConversationView], []),
  'createProject' : IDL.Func([IDL.Text], [ProjectView], []),
  'deleteConversation' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteFile' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'generateImage' : IDL.Func([IDL.Nat, IDL.Text], [ImageGenerationResult], []),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSubscription' : IDL.Func(
      [],
      [IDL.Opt(SubscriptionStatusView)],
      ['query'],
    ),
  'getUserSettings' : IDL.Func([], [IDL.Opt(UserSettingsView)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listConversations' : IDL.Func(
      [],
      [IDL.Vec(ChatConversationView)],
      ['query'],
    ),
  'listFiles' : IDL.Func([], [IDL.Vec(SavedFileView)], ['query']),
  'listGenerations' : IDL.Func([], [IDL.Vec(GenerationView)], ['query']),
  'listMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessageView)], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(ProjectView)], ['query']),
  'renameProject' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(ProjectView)], []),
  'saveFile' : IDL.Func([IDL.Opt(IDL.Nat), FileUpload], [Result], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'updateSubscription' : IDL.Func(
      [SubscriptionTier, IDL.Opt(Timestamp)],
      [SubscriptionStatusView],
      [],
    ),
  'updateUserSettings' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [UserSettingsView],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const ChatRole = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
  const ChatMessageView = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'owner' : UserId,
    'createdAt' : Timestamp,
    'role' : ChatRole,
    'conversationId' : IDL.Nat,
  });
  const DateRange = IDL.Variant({
    'today' : IDL.Null,
    'last90Days' : IDL.Null,
    'custom' : IDL.Record({ 'to' : Timestamp, 'from' : Timestamp }),
    'last7Days' : IDL.Null,
    'last30Days' : IDL.Null,
  });
  const CsvExport = IDL.Record({ 'content' : IDL.Text, 'filename' : IDL.Text });
  const ChartRange = IDL.Variant({
    'last90Days' : IDL.Null,
    'last7Days' : IDL.Null,
    'last30Days' : IDL.Null,
  });
  const ChartPoint = IDL.Record({
    'activeUsers' : IDL.Nat,
    'date' : Timestamp,
    'retentionRate' : IDL.Opt(IDL.Float64),
    'newUsers' : IDL.Nat,
  });
  const ChartSeries = IDL.Record({
    'range' : ChartRange,
    'points' : IDL.Vec(ChartPoint),
  });
  const ConnectionStatus = IDL.Variant({
    'notConnected' : IDL.Null,
    'connected' : IDL.Null,
  });
  const RevenueSummary = IDL.Record({
    'status' : ConnectionStatus,
    'today' : IDL.Nat,
    'total' : IDL.Nat,
    'subscription' : IDL.Nat,
    'thisWeek' : IDL.Nat,
    'oneTime' : IDL.Nat,
    'thisMonth' : IDL.Nat,
    'advertisement' : IDL.Nat,
  });
  const ProfitSummary = IDL.Record({
    'status' : ConnectionStatus,
    'otherCosts' : IDL.Nat,
    'aiApiCost' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'profitMargin' : IDL.Opt(IDL.Float64),
    'estimatedProfit' : IDL.Nat,
  });
  const DashboardOverview = IDL.Record({
    'premiumUsers' : IDL.Nat,
    'newUsersToday' : IDL.Nat,
    'activeUsersThisMonth' : IDL.Nat,
    'activeUsersToday' : IDL.Nat,
    'totalGenerations' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalRevenue' : RevenueSummary,
    'estimatedProfit' : ProfitSummary,
  });
  const FeatureUsage = IDL.Record({
    'numberOfUsers' : IDL.Nat,
    'failedGenerations' : IDL.Nat,
    'tool' : IDL.Text,
    'totalGenerations' : IDL.Nat,
    'successfulGenerations' : IDL.Nat,
    'averageGenerationsPerUser' : IDL.Opt(IDL.Float64),
  });
  const AdminSettingsView = IDL.Record({ 'otherCosts' : IDL.Nat });
  const SubscriptionMetrics = IDL.Record({
    'premiumUsers' : IDL.Nat,
    'subscriptionRevenue' : RevenueSummary,
    'newSubscriptions' : IDL.Nat,
    'renewals' : IDL.Nat,
    'freeUsers' : IDL.Nat,
    'activeSubscriptions' : IDL.Nat,
    'cancelledSubscriptions' : IDL.Nat,
  });
  const UserMetrics = IDL.Record({
    'newToday' : IDL.Nat,
    'newThisWeek' : IDL.Nat,
    'monthlyActive' : IDL.Nat,
    'newThisMonth' : IDL.Nat,
    'totalRegistered' : IDL.Nat,
    'dailyActive' : IDL.Nat,
    'retentionRate' : IDL.Opt(IDL.Float64),
    'returningUsers' : IDL.Nat,
  });
  const AccountStatus = IDL.Variant({
    'active' : IDL.Null,
    'disabled' : IDL.Null,
  });
  const SubscriptionTier = IDL.Variant({ 'pro' : IDL.Null, 'free' : IDL.Null });
  const SubscriptionStatusView = IDL.Record({
    'expiresAt' : IDL.Opt(Timestamp),
    'owner' : UserId,
    'tier' : SubscriptionTier,
  });
  const AdminUserRow = IDL.Record({
    'id' : UserId,
    'accountStatus' : AccountStatus,
    'lastActiveAt' : Timestamp,
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'subscriptionStatus' : SubscriptionStatusView,
    'aiGenerations' : IDL.Nat,
    'totalAmountSpent' : IDL.Nat,
    'registeredAt' : Timestamp,
  });
  const AnalyticsEventType = IDL.Variant({
    'generationCompleted' : IDL.Null,
    'subscriptionStarted' : IDL.Null,
    'registration' : IDL.Null,
    'generationStarted' : IDL.Null,
    'login' : IDL.Null,
    'subscriptionRenewed' : IDL.Null,
    'generationFailed' : IDL.Null,
    'paymentCompleted' : IDL.Null,
    'subscriptionCancelled' : IDL.Null,
  });
  const AnalyticsEventView = IDL.Record({
    'id' : IDL.Nat,
    'metadata' : IDL.Opt(IDL.Text),
    'user' : UserId,
    'timestamp' : Timestamp,
    'eventType' : AnalyticsEventType,
  });
  const UserDetail = IDL.Record({
    'metrics' : UserMetrics,
    'user' : AdminUserRow,
    'featureUsage' : IDL.Vec(FeatureUsage),
    'recentEvents' : IDL.Vec(AnalyticsEventView),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChatResult = IDL.Variant({
    'ok' : IDL.Record({ 'message' : IDL.Text }),
    'providerNotConfigured' : IDL.Null,
  });
  const ChatConversationView = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'owner' : UserId,
    'createdAt' : Timestamp,
  });
  const ProjectView = IDL.Record({
    'id' : IDL.Nat,
    'owner' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const ImageGenerationResult = IDL.Variant({
    'ok' : IDL.Record({ 'generationId' : IDL.Nat }),
    'providerNotConfigured' : IDL.Null,
  });
  const UserSettingsView = IDL.Record({
    'theme' : IDL.Text,
    'notificationsEnabled' : IDL.Bool,
    'displayName' : IDL.Text,
    'owner' : UserId,
    'email' : IDL.Opt(IDL.Text),
    'language' : IDL.Text,
  });
  const SavedFileView = IDL.Record({
    'id' : IDL.Nat,
    'owner' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'mimeType' : IDL.Text,
    'projectId' : IDL.Opt(IDL.Nat),
    'sizeBytes' : IDL.Nat,
  });
  const GenerationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const GenerationView = IDL.Record({
    'id' : IDL.Nat,
    'status' : GenerationStatus,
    'owner' : UserId,
    'createdAt' : Timestamp,
    'tool' : IDL.Text,
    'projectId' : IDL.Nat,
  });
  const FileUpload = IDL.Record({
    'name' : IDL.Text,
    'mimeType' : IDL.Text,
    'sizeBytes' : IDL.Nat,
  });
  const FileUploadError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'tooLarge' : IDL.Nat,
    'unsupportedType' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : SavedFileView, 'err' : FileUploadError });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addMessage' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(ChatMessageView)],
        [],
      ),
    'adminExportAnalyticsCsv' : IDL.Func(
        [IDL.Opt(DateRange)],
        [CsvExport],
        ['query'],
      ),
    'adminExportUsersCsv' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(DateRange)],
        [CsvExport],
        ['query'],
      ),
    'adminGetChartSeries' : IDL.Func([ChartRange], [ChartSeries], ['query']),
    'adminGetDashboardOverview' : IDL.Func([], [DashboardOverview], ['query']),
    'adminGetFeatureUsage' : IDL.Func([], [IDL.Vec(FeatureUsage)], ['query']),
    'adminGetSettings' : IDL.Func([], [AdminSettingsView], ['query']),
    'adminGetSubscriptionMetrics' : IDL.Func(
        [],
        [SubscriptionMetrics],
        ['query'],
      ),
    'adminGetUserDetail' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserDetail)],
        ['query'],
      ),
    'adminGetUserMetrics' : IDL.Func([], [UserMetrics], ['query']),
    'adminListUsers' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(DateRange)],
        [IDL.Vec(AdminUserRow)],
        ['query'],
      ),
    'adminUpdateOtherCosts' : IDL.Func([IDL.Nat], [AdminSettingsView], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'chat' : IDL.Func([IDL.Nat, IDL.Text], [ChatResult], []),
    'createConversation' : IDL.Func([IDL.Text], [ChatConversationView], []),
    'createProject' : IDL.Func([IDL.Text], [ProjectView], []),
    'deleteConversation' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteFile' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'generateImage' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [ImageGenerationResult],
        [],
      ),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSubscription' : IDL.Func(
        [],
        [IDL.Opt(SubscriptionStatusView)],
        ['query'],
      ),
    'getUserSettings' : IDL.Func([], [IDL.Opt(UserSettingsView)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listConversations' : IDL.Func(
        [],
        [IDL.Vec(ChatConversationView)],
        ['query'],
      ),
    'listFiles' : IDL.Func([], [IDL.Vec(SavedFileView)], ['query']),
    'listGenerations' : IDL.Func([], [IDL.Vec(GenerationView)], ['query']),
    'listMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessageView)], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(ProjectView)], ['query']),
    'renameProject' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(ProjectView)], []),
    'saveFile' : IDL.Func([IDL.Opt(IDL.Nat), FileUpload], [Result], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'updateSubscription' : IDL.Func(
        [SubscriptionTier, IDL.Opt(Timestamp)],
        [SubscriptionStatusView],
        [],
      ),
    'updateUserSettings' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [UserSettingsView],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };