/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type FileUploadError = {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "tooLarge";
    tooLarge: bigint;
} | {
    __kind__: "unsupportedType";
    unsupportedType: string;
};
export type Timestamp = bigint;
export interface AnalyticsEventView {
    id: bigint;
    metadata?: string;
    user: UserId;
    timestamp: Timestamp;
    eventType: AnalyticsEventType;
}
export interface AdminUserRow {
    id: UserId;
    accountStatus: AccountStatus;
    lastActiveAt: Timestamp;
    name: string;
    email?: string;
    subscriptionStatus: SubscriptionStatusView;
    aiGenerations: bigint;
    totalAmountSpent: bigint;
    registeredAt: Timestamp;
}
export interface Result__1 {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result_1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface FileUpload {
    name: string;
    mimeType: string;
    sizeBytes: bigint;
}
export interface UserDetail {
    metrics: UserMetrics;
    user: AdminUserRow;
    featureUsage: Array<FeatureUsage>;
    recentEvents: Array<AnalyticsEventView>;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface FeatureUsage {
    numberOfUsers: bigint;
    failedGenerations: bigint;
    tool: string;
    totalGenerations: bigint;
    successfulGenerations: bigint;
    averageGenerationsPerUser?: number;
}
export interface ProfitSummary {
    status: ConnectionStatus;
    otherCosts: bigint;
    aiApiCost: bigint;
    totalRevenue: bigint;
    profitMargin?: number;
    estimatedProfit: bigint;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface CsvExport {
    content: string;
    filename: string;
}
export type ChatResult = {
    __kind__: "ok";
    ok: {
        message: string;
    };
} | {
    __kind__: "providerNotConfigured";
    providerNotConfigured: null;
};
export interface SubscriptionMetrics {
    premiumUsers: bigint;
    subscriptionRevenue: RevenueSummary;
    newSubscriptions: bigint;
    renewals: bigint;
    freeUsers: bigint;
    activeSubscriptions: bigint;
    cancelledSubscriptions: bigint;
}
export interface GenerationView {
    id: bigint;
    status: GenerationStatus;
    owner: UserId;
    createdAt: Timestamp;
    tool: string;
    projectId: bigint;
}
export interface ChartSeries {
    range: ChartRange;
    points: Array<ChartPoint>;
}
export interface SavedFileView {
    id: bigint;
    owner: UserId;
    name: string;
    createdAt: Timestamp;
    mimeType: string;
    projectId?: bigint;
    sizeBytes: bigint;
}
export interface ProjectView {
    id: bigint;
    owner: UserId;
    name: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
}
export interface SubscriptionStatusView {
    expiresAt?: Timestamp;
    owner: UserId;
    tier: SubscriptionTier;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface RevenueSummary {
    status: ConnectionStatus;
    today: bigint;
    total: bigint;
    subscription: bigint;
    thisWeek: bigint;
    oneTime: bigint;
    thisMonth: bigint;
    advertisement: bigint;
}
export type UserId = Principal;
export type DateRange = {
    __kind__: "today";
    today: null;
} | {
    __kind__: "last90Days";
    last90Days: null;
} | {
    __kind__: "custom";
    custom: {
        to: Timestamp;
        from: Timestamp;
    };
} | {
    __kind__: "last7Days";
    last7Days: null;
} | {
    __kind__: "last30Days";
    last30Days: null;
};
export type Result = {
    __kind__: "ok";
    ok: SavedFileView;
} | {
    __kind__: "err";
    err: FileUploadError;
};
export interface ChartPoint {
    activeUsers: bigint;
    date: Timestamp;
    retentionRate?: number;
    newUsers: bigint;
}
export type ImageGenerationResult = {
    __kind__: "ok";
    ok: {
        generationId: bigint;
    };
} | {
    __kind__: "providerNotConfigured";
    providerNotConfigured: null;
};
export interface ChatMessageView {
    id: bigint;
    content: string;
    owner: UserId;
    createdAt: Timestamp;
    role: ChatRole;
    conversationId: bigint;
}
export interface AdminSettingsView {
    otherCosts: bigint;
}
export interface UserSettingsView {
    theme: string;
    notificationsEnabled: boolean;
    displayName: string;
    owner: UserId;
    email?: string;
    language: string;
}
export interface ChatConversationView {
    id: bigint;
    title: string;
    owner: UserId;
    createdAt: Timestamp;
}
export interface UserMetrics {
    newToday: bigint;
    newThisWeek: bigint;
    monthlyActive: bigint;
    newThisMonth: bigint;
    totalRegistered: bigint;
    dailyActive: bigint;
    retentionRate?: number;
    returningUsers: bigint;
}
export interface DashboardOverview {
    premiumUsers: bigint;
    newUsersToday: bigint;
    activeUsersThisMonth: bigint;
    activeUsersToday: bigint;
    totalGenerations: bigint;
    totalUsers: bigint;
    totalRevenue: RevenueSummary;
    estimatedProfit: ProfitSummary;
}
export enum AccountStatus {
    active = "active",
    disabled = "disabled"
}
export enum AnalyticsEventType {
    generationCompleted = "generationCompleted",
    subscriptionStarted = "subscriptionStarted",
    registration = "registration",
    generationStarted = "generationStarted",
    login = "login",
    subscriptionRenewed = "subscriptionRenewed",
    generationFailed = "generationFailed",
    paymentCompleted = "paymentCompleted",
    subscriptionCancelled = "subscriptionCancelled"
}
export enum ChartRange {
    last90Days = "last90Days",
    last7Days = "last7Days",
    last30Days = "last30Days"
}
export enum ChatRole {
    user = "user",
    assistant = "assistant"
}
export enum ConnectionStatus {
    notConnected = "notConnected",
    connected = "connected"
}
export enum GenerationStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum SubscriptionTier {
    pro = "pro",
    free = "free"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result_1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addMessage(conversationId: bigint, content: string): Promise<ChatMessageView | null>;
    adminExportAnalyticsCsv(dateRange: DateRange | null): Promise<CsvExport>;
    adminExportUsersCsv(search: string | null, dateRange: DateRange | null): Promise<CsvExport>;
    adminGetChartSeries(range: ChartRange): Promise<ChartSeries>;
    adminGetDashboardOverview(): Promise<DashboardOverview>;
    adminGetFeatureUsage(): Promise<Array<FeatureUsage>>;
    adminGetSettings(): Promise<AdminSettingsView>;
    adminGetSubscriptionMetrics(): Promise<SubscriptionMetrics>;
    adminGetUserDetail(userId: Principal): Promise<UserDetail | null>;
    adminGetUserMetrics(): Promise<UserMetrics>;
    adminListUsers(search: string | null, dateRange: DateRange | null): Promise<Array<AdminUserRow>>;
    adminUpdateOtherCosts(otherCosts: bigint): Promise<AdminSettingsView>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    chat(conversationId: bigint, message: string): Promise<ChatResult>;
    createConversation(title: string): Promise<ChatConversationView>;
    createProject(name: string): Promise<ProjectView>;
    deleteConversation(conversationId: bigint): Promise<boolean>;
    deleteFile(fileId: bigint): Promise<boolean>;
    deleteProject(projectId: bigint): Promise<boolean>;
    execute(qJson: string): Promise<Result__1>;
    generateImage(projectId: bigint, prompt: string): Promise<ImageGenerationResult>;
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    getSubscription(): Promise<SubscriptionStatusView | null>;
    getUserSettings(): Promise<UserSettingsView | null>;
    isCallerAdmin(): Promise<boolean>;
    listConversations(): Promise<Array<ChatConversationView>>;
    listFiles(): Promise<Array<SavedFileView>>;
    listGenerations(): Promise<Array<GenerationView>>;
    listMessages(conversationId: bigint): Promise<Array<ChatMessageView>>;
    listProjects(): Promise<Array<ProjectView>>;
    renameProject(projectId: bigint, name: string): Promise<ProjectView | null>;
    saveFile(projectId: bigint | null, upload: FileUpload): Promise<Result>;
    schema(): Promise<string>;
    updateSubscription(tier: SubscriptionTier, expiresAt: Timestamp | null): Promise<SubscriptionStatusView>;
    updateUserSettings(theme: string, notificationsEnabled: boolean, displayName: string, email: string | null, language: string): Promise<UserSettingsView>;
}
import type { AccountStatus as _AccountStatus, AdminUserRow as _AdminUserRow, AnalyticsEventType as _AnalyticsEventType, AnalyticsEventView as _AnalyticsEventView, Cell as _Cell, ChartPoint as _ChartPoint, ChartRange as _ChartRange, ChartSeries as _ChartSeries, ChatMessageView as _ChatMessageView, ChatResult as _ChatResult, ChatRole as _ChatRole, ConnectionStatus as _ConnectionStatus, DashboardOverview as _DashboardOverview, DateRange as _DateRange, Error as _Error, FeatureUsage as _FeatureUsage, FileUploadError as _FileUploadError, GenerationStatus as _GenerationStatus, GenerationView as _GenerationView, ImageGenerationResult as _ImageGenerationResult, ProfitSummary as _ProfitSummary, ProjectView as _ProjectView, Result as _Result, Result_1 as _Result_1, Result__1 as _Result__1, RevenueSummary as _RevenueSummary, SavedFileView as _SavedFileView, SubscriptionMetrics as _SubscriptionMetrics, SubscriptionStatusView as _SubscriptionStatusView, SubscriptionTier as _SubscriptionTier, Timestamp as _Timestamp, UserDetail as _UserDetail, UserId as _UserId, UserMetrics as _UserMetrics, UserRole as _UserRole, UserSettingsView as _UserSettingsView, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addMessage(arg0: bigint, arg1: string): Promise<ChatMessageView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addMessage(arg0, arg1);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMessage(arg0, arg1);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminExportAnalyticsCsv(arg0: DateRange | null): Promise<CsvExport> {
        if (this.processError) {
            try {
                const result = await this.actor.adminExportAnalyticsCsv(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminExportAnalyticsCsv(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async adminExportUsersCsv(arg0: string | null, arg1: DateRange | null): Promise<CsvExport> {
        if (this.processError) {
            try {
                const result = await this.actor.adminExportUsersCsv(to_candid_opt_n13(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminExportUsersCsv(to_candid_opt_n13(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async adminGetChartSeries(arg0: ChartRange): Promise<ChartSeries> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetChartSeries(to_candid_ChartRange_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ChartSeries_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetChartSeries(to_candid_ChartRange_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ChartSeries_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetDashboardOverview(): Promise<DashboardOverview> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetDashboardOverview();
                return from_candid_DashboardOverview_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetDashboardOverview();
            return from_candid_DashboardOverview_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetFeatureUsage(): Promise<Array<FeatureUsage>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetFeatureUsage();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetFeatureUsage();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetSettings(): Promise<AdminSettingsView> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetSettings();
            return result;
        }
    }
    async adminGetSubscriptionMetrics(): Promise<SubscriptionMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetSubscriptionMetrics();
                return from_candid_SubscriptionMetrics_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetSubscriptionMetrics();
            return from_candid_SubscriptionMetrics_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetUserDetail(arg0: Principal): Promise<UserDetail | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUserDetail(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUserDetail(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetUserMetrics(): Promise<UserMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUserMetrics();
                return from_candid_UserMetrics_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUserMetrics();
            return from_candid_UserMetrics_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListUsers(arg0: string | null, arg1: DateRange | null): Promise<Array<AdminUserRow>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListUsers(to_candid_opt_n13(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListUsers(to_candid_opt_n13(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateOtherCosts(arg0: bigint): Promise<AdminSettingsView> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateOtherCosts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateOtherCosts(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n58(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n58(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async chat(arg0: bigint, arg1: string): Promise<ChatResult> {
        if (this.processError) {
            try {
                const result = await this.actor.chat(arg0, arg1);
                return from_candid_ChatResult_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.chat(arg0, arg1);
            return from_candid_ChatResult_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async createConversation(arg0: string): Promise<ChatConversationView> {
        if (this.processError) {
            try {
                const result = await this.actor.createConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createConversation(arg0);
            return result;
        }
    }
    async createProject(arg0: string): Promise<ProjectView> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0);
            return result;
        }
    }
    async deleteConversation(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteConversation(arg0);
            return result;
        }
    }
    async deleteFile(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFile(arg0);
            return result;
        }
    }
    async deleteProject(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result__1_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result__1_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateImage(arg0: bigint, arg1: string): Promise<ImageGenerationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.generateImage(arg0, arg1);
                return from_candid_ImageGenerationResult_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateImage(arg0, arg1);
            return from_candid_ImageGenerationResult_n70(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n72(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n72(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscription(): Promise<SubscriptionStatusView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscription();
                return from_candid_opt_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscription();
            return from_candid_opt_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSettings(): Promise<UserSettingsView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSettings();
                return from_candid_opt_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSettings();
            return from_candid_opt_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listConversations(): Promise<Array<ChatConversationView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listConversations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listConversations();
            return result;
        }
    }
    async listFiles(): Promise<Array<SavedFileView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFiles();
                return from_candid_vec_n78(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFiles();
            return from_candid_vec_n78(this._uploadFile, this._downloadFile, result);
        }
    }
    async listGenerations(): Promise<Array<GenerationView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGenerations();
                return from_candid_vec_n82(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGenerations();
            return from_candid_vec_n82(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMessages(arg0: bigint): Promise<Array<ChatMessageView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMessages(arg0);
                return from_candid_vec_n87(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMessages(arg0);
            return from_candid_vec_n87(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProjects(): Promise<Array<ProjectView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjects();
            return result;
        }
    }
    async renameProject(arg0: bigint, arg1: string): Promise<ProjectView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.renameProject(arg0, arg1);
                return from_candid_opt_n88(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameProject(arg0, arg1);
            return from_candid_opt_n88(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveFile(arg0: bigint | null, arg1: FileUpload): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFile(to_candid_opt_n89(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_Result_n90(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFile(to_candid_opt_n89(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_Result_n90(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async updateSubscription(arg0: SubscriptionTier, arg1: Timestamp | null): Promise<SubscriptionStatusView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubscription(to_candid_SubscriptionTier_n94(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n96(this._uploadFile, this._downloadFile, arg1));
                return from_candid_SubscriptionStatusView_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubscription(to_candid_SubscriptionTier_n94(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n96(this._uploadFile, this._downloadFile, arg1));
            return from_candid_SubscriptionStatusView_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserSettings(arg0: string, arg1: boolean, arg2: string, arg3: string | null, arg4: string): Promise<UserSettingsView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserSettings(arg0, arg1, arg2, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_UserSettingsView_n76(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserSettings(arg0, arg1, arg2, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_UserSettingsView_n76(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AccountStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountStatus): AccountStatus {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_AdminUserRow_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminUserRow): AdminUserRow {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_AnalyticsEventType_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalyticsEventType): AnalyticsEventType {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function from_candid_AnalyticsEventView_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalyticsEventView): AnalyticsEventView {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n67(_uploadFile, _downloadFile, value);
}
function from_candid_ChartPoint_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChartPoint): ChartPoint {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ChartRange_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChartRange): ChartRange {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ChartSeries_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChartSeries): ChartSeries {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ChatMessageView_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessageView): ChatMessageView {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ChatResult_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatResult): ChatResult {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_ChatRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatRole): ChatRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ConnectionStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConnectionStatus): ConnectionStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_DashboardOverview_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardOverview): DashboardOverview {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_FeatureUsage_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeatureUsage): FeatureUsage {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_FileUploadError_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileUploadError): FileUploadError {
    return from_candid_variant_n93(_uploadFile, _downloadFile, value);
}
function from_candid_GenerationStatus_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GenerationStatus): GenerationStatus {
    return from_candid_variant_n86(_uploadFile, _downloadFile, value);
}
function from_candid_GenerationView_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GenerationView): GenerationView {
    return from_candid_record_n84(_uploadFile, _downloadFile, value);
}
function from_candid_ImageGenerationResult_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImageGenerationResult): ImageGenerationResult {
    return from_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function from_candid_ProfitSummary_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfitSummary): ProfitSummary {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_record_n63(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n91(_uploadFile, _downloadFile, value);
}
function from_candid_RevenueSummary_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RevenueSummary): RevenueSummary {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_SavedFileView_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SavedFileView): SavedFileView {
    return from_candid_record_n80(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionMetrics_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionMetrics): SubscriptionMetrics {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatusView_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatusView): SubscriptionStatusView {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionTier_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionTier): SubscriptionTier {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_UserDetail_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserDetail): UserDetail {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_UserMetrics_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserMetrics): UserMetrics {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n73(_uploadFile, _downloadFile, value);
}
function from_candid_UserSettingsView_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserSettingsView): UserSettingsView {
    return from_candid_record_n77(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserDetail]): UserDetail | null {
    return value.length === 0 ? null : from_candid_UserDetail_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChatMessageView]): ChatMessageView | null {
    return value.length === 0 ? null : from_candid_ChatMessageView_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubscriptionStatusView]): SubscriptionStatusView | null {
    return value.length === 0 ? null : from_candid_SubscriptionStatusView_n47(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserSettingsView]): UserSettingsView | null {
    return value.length === 0 ? null : from_candid_UserSettingsView_n76(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProjectView]): ProjectView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    range: _ChartRange;
    points: Array<_ChartPoint>;
}): {
    range: ChartRange;
    points: Array<ChartPoint>;
} {
    return {
        range: from_candid_ChartRange_n18(_uploadFile, _downloadFile, value.range),
        points: from_candid_vec_n20(_uploadFile, _downloadFile, value.points)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    activeUsers: bigint;
    date: _Timestamp;
    retentionRate: [] | [number];
    newUsers: bigint;
}): {
    activeUsers: bigint;
    date: Timestamp;
    retentionRate?: number;
    newUsers: bigint;
} {
    return {
        activeUsers: value.activeUsers,
        date: value.date,
        retentionRate: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.retentionRate)),
        newUsers: value.newUsers
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premiumUsers: bigint;
    newUsersToday: bigint;
    activeUsersThisMonth: bigint;
    activeUsersToday: bigint;
    totalGenerations: bigint;
    totalUsers: bigint;
    totalRevenue: _RevenueSummary;
    estimatedProfit: _ProfitSummary;
}): {
    premiumUsers: bigint;
    newUsersToday: bigint;
    activeUsersThisMonth: bigint;
    activeUsersToday: bigint;
    totalGenerations: bigint;
    totalUsers: bigint;
    totalRevenue: RevenueSummary;
    estimatedProfit: ProfitSummary;
} {
    return {
        premiumUsers: value.premiumUsers,
        newUsersToday: value.newUsersToday,
        activeUsersThisMonth: value.activeUsersThisMonth,
        activeUsersToday: value.activeUsersToday,
        totalGenerations: value.totalGenerations,
        totalUsers: value.totalUsers,
        totalRevenue: from_candid_RevenueSummary_n26(_uploadFile, _downloadFile, value.totalRevenue),
        estimatedProfit: from_candid_ProfitSummary_n30(_uploadFile, _downloadFile, value.estimatedProfit)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ConnectionStatus;
    today: bigint;
    total: bigint;
    subscription: bigint;
    thisWeek: bigint;
    oneTime: bigint;
    thisMonth: bigint;
    advertisement: bigint;
}): {
    status: ConnectionStatus;
    today: bigint;
    total: bigint;
    subscription: bigint;
    thisWeek: bigint;
    oneTime: bigint;
    thisMonth: bigint;
    advertisement: bigint;
} {
    return {
        status: from_candid_ConnectionStatus_n28(_uploadFile, _downloadFile, value.status),
        today: value.today,
        total: value.total,
        subscription: value.subscription,
        thisWeek: value.thisWeek,
        oneTime: value.oneTime,
        thisMonth: value.thisMonth,
        advertisement: value.advertisement
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ConnectionStatus;
    otherCosts: bigint;
    aiApiCost: bigint;
    totalRevenue: bigint;
    profitMargin: [] | [number];
    estimatedProfit: bigint;
}): {
    status: ConnectionStatus;
    otherCosts: bigint;
    aiApiCost: bigint;
    totalRevenue: bigint;
    profitMargin?: number;
    estimatedProfit: bigint;
} {
    return {
        status: from_candid_ConnectionStatus_n28(_uploadFile, _downloadFile, value.status),
        otherCosts: value.otherCosts,
        aiApiCost: value.aiApiCost,
        totalRevenue: value.totalRevenue,
        profitMargin: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.profitMargin)),
        estimatedProfit: value.estimatedProfit
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    numberOfUsers: bigint;
    failedGenerations: bigint;
    tool: string;
    totalGenerations: bigint;
    successfulGenerations: bigint;
    averageGenerationsPerUser: [] | [number];
}): {
    numberOfUsers: bigint;
    failedGenerations: bigint;
    tool: string;
    totalGenerations: bigint;
    successfulGenerations: bigint;
    averageGenerationsPerUser?: number;
} {
    return {
        numberOfUsers: value.numberOfUsers,
        failedGenerations: value.failedGenerations,
        tool: value.tool,
        totalGenerations: value.totalGenerations,
        successfulGenerations: value.successfulGenerations,
        averageGenerationsPerUser: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.averageGenerationsPerUser))
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premiumUsers: bigint;
    subscriptionRevenue: _RevenueSummary;
    newSubscriptions: bigint;
    renewals: bigint;
    freeUsers: bigint;
    activeSubscriptions: bigint;
    cancelledSubscriptions: bigint;
}): {
    premiumUsers: bigint;
    subscriptionRevenue: RevenueSummary;
    newSubscriptions: bigint;
    renewals: bigint;
    freeUsers: bigint;
    activeSubscriptions: bigint;
    cancelledSubscriptions: bigint;
} {
    return {
        premiumUsers: value.premiumUsers,
        subscriptionRevenue: from_candid_RevenueSummary_n26(_uploadFile, _downloadFile, value.subscriptionRevenue),
        newSubscriptions: value.newSubscriptions,
        renewals: value.renewals,
        freeUsers: value.freeUsers,
        activeSubscriptions: value.activeSubscriptions,
        cancelledSubscriptions: value.cancelledSubscriptions
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metrics: _UserMetrics;
    user: _AdminUserRow;
    featureUsage: Array<_FeatureUsage>;
    recentEvents: Array<_AnalyticsEventView>;
}): {
    metrics: UserMetrics;
    user: AdminUserRow;
    featureUsage: Array<FeatureUsage>;
    recentEvents: Array<AnalyticsEventView>;
} {
    return {
        metrics: from_candid_UserMetrics_n40(_uploadFile, _downloadFile, value.metrics),
        user: from_candid_AdminUserRow_n42(_uploadFile, _downloadFile, value.user),
        featureUsage: from_candid_vec_n32(_uploadFile, _downloadFile, value.featureUsage),
        recentEvents: from_candid_vec_n52(_uploadFile, _downloadFile, value.recentEvents)
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    newToday: bigint;
    newThisWeek: bigint;
    monthlyActive: bigint;
    newThisMonth: bigint;
    totalRegistered: bigint;
    dailyActive: bigint;
    retentionRate: [] | [number];
    returningUsers: bigint;
}): {
    newToday: bigint;
    newThisWeek: bigint;
    monthlyActive: bigint;
    newThisMonth: bigint;
    totalRegistered: bigint;
    dailyActive: bigint;
    retentionRate?: number;
    returningUsers: bigint;
} {
    return {
        newToday: value.newToday,
        newThisWeek: value.newThisWeek,
        monthlyActive: value.monthlyActive,
        newThisMonth: value.newThisMonth,
        totalRegistered: value.totalRegistered,
        dailyActive: value.dailyActive,
        retentionRate: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.retentionRate)),
        returningUsers: value.returningUsers
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    accountStatus: _AccountStatus;
    lastActiveAt: _Timestamp;
    name: string;
    email: [] | [string];
    subscriptionStatus: _SubscriptionStatusView;
    aiGenerations: bigint;
    totalAmountSpent: bigint;
    registeredAt: _Timestamp;
}): {
    id: UserId;
    accountStatus: AccountStatus;
    lastActiveAt: Timestamp;
    name: string;
    email?: string;
    subscriptionStatus: SubscriptionStatusView;
    aiGenerations: bigint;
    totalAmountSpent: bigint;
    registeredAt: Timestamp;
} {
    return {
        id: value.id,
        accountStatus: from_candid_AccountStatus_n44(_uploadFile, _downloadFile, value.accountStatus),
        lastActiveAt: value.lastActiveAt,
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.email)),
        subscriptionStatus: from_candid_SubscriptionStatusView_n47(_uploadFile, _downloadFile, value.subscriptionStatus),
        aiGenerations: value.aiGenerations,
        totalAmountSpent: value.totalAmountSpent,
        registeredAt: value.registeredAt
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expiresAt: [] | [_Timestamp];
    owner: _UserId;
    tier: _SubscriptionTier;
}): {
    expiresAt?: Timestamp;
    owner: UserId;
    tier: SubscriptionTier;
} {
    return {
        expiresAt: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.expiresAt)),
        owner: value.owner,
        tier: from_candid_SubscriptionTier_n50(_uploadFile, _downloadFile, value.tier)
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    metadata: [] | [string];
    user: _UserId;
    timestamp: _Timestamp;
    eventType: _AnalyticsEventType;
}): {
    id: bigint;
    metadata?: string;
    user: UserId;
    timestamp: Timestamp;
    eventType: AnalyticsEventType;
} {
    return {
        id: value.id,
        metadata: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.metadata)),
        user: value.user,
        timestamp: value.timestamp,
        eventType: from_candid_AnalyticsEventType_n55(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n64(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n68(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    owner: _UserId;
    createdAt: _Timestamp;
    role: _ChatRole;
    conversationId: bigint;
}): {
    id: bigint;
    content: string;
    owner: UserId;
    createdAt: Timestamp;
    role: ChatRole;
    conversationId: bigint;
} {
    return {
        id: value.id,
        content: value.content,
        owner: value.owner,
        createdAt: value.createdAt,
        role: from_candid_ChatRole_n8(_uploadFile, _downloadFile, value.role),
        conversationId: value.conversationId
    };
}
function from_candid_record_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: string;
    notificationsEnabled: boolean;
    displayName: string;
    owner: _UserId;
    email: [] | [string];
    language: string;
}): {
    theme: string;
    notificationsEnabled: boolean;
    displayName: string;
    owner: UserId;
    email?: string;
    language: string;
} {
    return {
        theme: value.theme,
        notificationsEnabled: value.notificationsEnabled,
        displayName: value.displayName,
        owner: value.owner,
        email: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.email)),
        language: value.language
    };
}
function from_candid_record_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    owner: _UserId;
    name: string;
    createdAt: _Timestamp;
    mimeType: string;
    projectId: [] | [bigint];
    sizeBytes: bigint;
}): {
    id: bigint;
    owner: UserId;
    name: string;
    createdAt: Timestamp;
    mimeType: string;
    projectId?: bigint;
    sizeBytes: bigint;
} {
    return {
        id: value.id,
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        mimeType: value.mimeType,
        projectId: record_opt_to_undefined(from_candid_opt_n81(_uploadFile, _downloadFile, value.projectId)),
        sizeBytes: value.sizeBytes
    };
}
function from_candid_record_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _GenerationStatus;
    owner: _UserId;
    createdAt: _Timestamp;
    tool: string;
    projectId: bigint;
}): {
    id: bigint;
    status: GenerationStatus;
    owner: UserId;
    createdAt: Timestamp;
    tool: string;
    projectId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_GenerationStatus_n85(_uploadFile, _downloadFile, value.status),
        owner: value.owner,
        createdAt: value.createdAt,
        tool: value.tool,
        projectId: value.projectId
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    last90Days: null;
} | {
    last7Days: null;
} | {
    last30Days: null;
}): ChartRange {
    return "last90Days" in value ? ChartRange.last90Days : "last7Days" in value ? ChartRange.last7Days : "last30Days" in value ? ChartRange.last30Days : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notConnected: null;
} | {
    connected: null;
}): ConnectionStatus {
    return "notConnected" in value ? ConnectionStatus.notConnected : "connected" in value ? ConnectionStatus.connected : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    disabled: null;
}): AccountStatus {
    return "active" in value ? AccountStatus.active : "disabled" in value ? AccountStatus.disabled : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pro: null;
} | {
    free: null;
}): SubscriptionTier {
    return "pro" in value ? SubscriptionTier.pro : "free" in value ? SubscriptionTier.free : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    generationCompleted: null;
} | {
    subscriptionStarted: null;
} | {
    registration: null;
} | {
    generationStarted: null;
} | {
    login: null;
} | {
    subscriptionRenewed: null;
} | {
    generationFailed: null;
} | {
    paymentCompleted: null;
} | {
    subscriptionCancelled: null;
}): AnalyticsEventType {
    return "generationCompleted" in value ? AnalyticsEventType.generationCompleted : "subscriptionStarted" in value ? AnalyticsEventType.subscriptionStarted : "registration" in value ? AnalyticsEventType.registration : "generationStarted" in value ? AnalyticsEventType.generationStarted : "login" in value ? AnalyticsEventType.login : "subscriptionRenewed" in value ? AnalyticsEventType.subscriptionRenewed : "generationFailed" in value ? AnalyticsEventType.generationFailed : "paymentCompleted" in value ? AnalyticsEventType.paymentCompleted : "subscriptionCancelled" in value ? AnalyticsEventType.subscriptionCancelled : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        message: string;
    };
} | {
    providerNotConfigured: null;
}): {
    __kind__: "ok";
    ok: {
        message: string;
    };
} | {
    __kind__: "providerNotConfigured";
    providerNotConfigured: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "providerNotConfigured" in value ? {
        __kind__: "providerNotConfigured",
        providerNotConfigured: value.providerNotConfigured
    } : value;
}
function from_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        generationId: bigint;
    };
} | {
    providerNotConfigured: null;
}): {
    __kind__: "ok";
    ok: {
        generationId: bigint;
    };
} | {
    __kind__: "providerNotConfigured";
    providerNotConfigured: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "providerNotConfigured" in value ? {
        __kind__: "providerNotConfigured",
        providerNotConfigured: value.providerNotConfigured
    } : value;
}
function from_candid_variant_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): GenerationStatus {
    return "pending" in value ? GenerationStatus.pending : "completed" in value ? GenerationStatus.completed : "failed" in value ? GenerationStatus.failed : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: null;
} | {
    assistant: null;
}): ChatRole {
    return "user" in value ? ChatRole.user : "assistant" in value ? ChatRole.assistant : value;
}
function from_candid_variant_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SavedFileView;
} | {
    err: _FileUploadError;
}): {
    __kind__: "ok";
    ok: SavedFileView;
} | {
    __kind__: "err";
    err: FileUploadError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_SavedFileView_n79(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_FileUploadError_n92(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notAuthorized: null;
} | {
    tooLarge: bigint;
} | {
    unsupportedType: string;
}): {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "tooLarge";
    tooLarge: bigint;
} | {
    __kind__: "unsupportedType";
    unsupportedType: string;
} {
    return "notAuthorized" in value ? {
        __kind__: "notAuthorized",
        notAuthorized: value.notAuthorized
    } : "tooLarge" in value ? {
        __kind__: "tooLarge",
        tooLarge: value.tooLarge
    } : "unsupportedType" in value ? {
        __kind__: "unsupportedType",
        unsupportedType: value.unsupportedType
    } : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChartPoint>): Array<ChartPoint> {
    return value.map((x)=>from_candid_ChartPoint_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeatureUsage>): Array<FeatureUsage> {
    return value.map((x)=>from_candid_FeatureUsage_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnalyticsEventView>): Array<AnalyticsEventView> {
    return value.map((x)=>from_candid_AnalyticsEventView_n53(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminUserRow>): Array<AdminUserRow> {
    return value.map((x)=>from_candid_AdminUserRow_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n65(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n66(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SavedFileView>): Array<SavedFileView> {
    return value.map((x)=>from_candid_SavedFileView_n79(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GenerationView>): Array<GenerationView> {
    return value.map((x)=>from_candid_GenerationView_n83(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessageView>): Array<ChatMessageView> {
    return value.map((x)=>from_candid_ChatMessageView_n6(_uploadFile, _downloadFile, x));
}
function to_candid_ChartRange_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChartRange): _ChartRange {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_DateRange_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DateRange): _DateRange {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionTier_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): _SubscriptionTier {
    return to_candid_variant_n95(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DateRange | null): [] | [_DateRange] {
    return value === null ? candid_none() : candid_some(to_candid_DateRange_n11(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n96(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "today";
    today: null;
} | {
    __kind__: "last90Days";
    last90Days: null;
} | {
    __kind__: "custom";
    custom: {
        to: Timestamp;
        from: Timestamp;
    };
} | {
    __kind__: "last7Days";
    last7Days: null;
} | {
    __kind__: "last30Days";
    last30Days: null;
}): {
    today: null;
} | {
    last90Days: null;
} | {
    custom: {
        to: _Timestamp;
        from: _Timestamp;
    };
} | {
    last7Days: null;
} | {
    last30Days: null;
} {
    return value.__kind__ === "today" ? {
        today: value.today
    } : value.__kind__ === "last90Days" ? {
        last90Days: value.last90Days
    } : value.__kind__ === "custom" ? {
        custom: value.custom
    } : value.__kind__ === "last7Days" ? {
        last7Days: value.last7Days
    } : value.__kind__ === "last30Days" ? {
        last30Days: value.last30Days
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChartRange): {
    last90Days: null;
} | {
    last7Days: null;
} | {
    last30Days: null;
} {
    return value == ChartRange.last90Days ? {
        last90Days: null
    } : value == ChartRange.last7Days ? {
        last7Days: null
    } : value == ChartRange.last30Days ? {
        last30Days: null
    } : value;
}
function to_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): {
    pro: null;
} | {
    free: null;
} {
    return value == SubscriptionTier.pro ? {
        pro: null
    } : value == SubscriptionTier.free ? {
        free: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
